window.launchpadConfig = {
  owner: "totob12.com",
  showDisabled: false,
};

// access: "public" | "tailnet"
window.launchpadServices = [
  {
    name: "Plex",
    url: "https://avalon.totob12.com",
    access: "public",
    description: "Avalon media server",
    group: "Media",
    enabled: true,
    icon: "https://www.vectorlogo.zone/logos/plextv/plextv-icon.svg",
    tags: ["nas", "streaming", "avalon"],
  },
  {
    name: "Find",
    url: "https://find.totob12.com",
    access: "public",
    description: "PIN-protected live location sharing",
    group: "Maps",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/owntracks.svg",
    tags: ["location", "map", "owntracks"],
  },
  {
    name: "Fly Umwelt",
    url: "https://fly.totob12.com",
    access: "public",
    description: "Whole-connectome fruit-fly observatory",
    group: "Science",
    enabled: true,
    icon: "https://fly.totob12.com/favicon.svg",
    tags: ["science", "simulation", "connectome", "fruit fly"],
  },
  {
    name: "MoonDNS",
    url: "https://moondns.io",
    access: "public",
    description: "Private DNS controls with DoH, DoT, profiles, and filtering",
    group: "Network",
    enabled: true,
    icon: "./assets/icons/moondns.svg",
    tags: ["dns", "privacy", "filtering", "doh", "dot"],
  },
  {
    name: "Crash",
    url: "https://crash.totob12.com",
    access: "public",
    description: "Browser crash and resilience test page",
    group: "Experiments",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/npm/@mdi/svg@7.4.47/svg/alert-octagon-outline.svg",
    tags: ["browser", "crash", "test", "experiment"],
  },
  {
    name: "TotoB12 Chess",
    url: "https://chess.totob12.com",
    access: "public",
    description: "Play, analyse positions, and solve chess puzzles",
    group: "Games",
    enabled: true,
    icon: "https://raw.githubusercontent.com/TotoB12/chess/main/images/favicon.ico",
    tags: ["chess", "game", "analysis", "puzzles"],
  },
  {
    name: "Drive Dash",
    url: "https://drived.totob12.com",
    access: "public",
    description: "Live driving map with speed, road, and speed-limit display",
    group: "Maps",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/npm/@mdi/svg@7.4.47/svg/car-outline.svg",
    tags: ["driving", "map", "speed", "gps"],
  },
  {
    name: "Imabel",
    url: "https://imabel.totob12.com",
    access: "public",
    description: "Deterministic archive for bounded text and image spaces",
    group: "Knowledge",
    enabled: true,
    icon: "https://imabel.totob12.com/imabel-mark.png",
    tags: ["archive", "text", "images", "deterministic"],
  },
  {
    name: "Vaultwarden",
    url: "https://vaultwarden.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Private Bitwarden-compatible vault",
    group: "Security",
    enabled: true,
    icon: "https://www.vectorlogo.zone/logos/bitwarden/bitwarden-icon.svg",
    tags: ["passwords", "bitwarden"],
  },
  {
    name: "Anytype",
    url: "http://100.89.191.49",
    access: "tailnet",
    description: "Personal knowledge workspace",
    group: "Knowledge",
    enabled: true,
    icon: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Anytype_logo_%28B%26W%29.svg",
    tags: ["notes", "workspace"],
  },
  {
    name: "Dawarich",
    url: "https://dawarich.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Private location history",
    group: "Maps",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dawarich.svg",
    tags: ["location", "maps", "owntracks"],
  },
  {
    name: "OwnTracks Relay",
    url: "https://dawarich.tahr-vibe.ts.net/api/owntracks",
    access: "tailnet",
    description: "Shared ingest: forwards OwnTracks to Find and Dawarich",
    group: "Maps",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/owntracks.svg",
    tags: ["location", "api", "owntracks", "find", "dawarich", "node-red"],
  },
  {
    name: "Calibre-Web",
    url: "https://calibre.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Books and library shelf",
    group: "Knowledge",
    enabled: true,
    icon: "https://github.com/janeczku/calibre-web/blob/master/cps/static/icon.png?raw=true",
    tags: ["books", "library"],
  },
  {
    name: "BookOrbit",
    url: "https://bookorbit.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Private ebook library and reader",
    group: "Knowledge",
    enabled: true,
    icon: "https://raw.githubusercontent.com/bookorbit/bookorbit/main/client/public/pwa-icon-source.svg",
    tags: ["books", "ebooks", "library", "reader"],
  },
  {
    name: "Kiwix",
    url: "https://kiwix.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Offline Wikipedia archive",
    group: "Knowledge",
    enabled: true,
    icon: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Kiwix_logo_v3.svg",
    tags: ["wikipedia", "archive"],
  },
  {
    name: "Speedtest Tracker",
    url: "https://speedtest.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Network speed history",
    group: "Operations",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/speedtest-tracker.png",
    tags: ["network", "monitoring"],
  },
  {
    name: "Dispatcharr",
    url: "https://dispatcharr.tahr-vibe.ts.net",
    access: "tailnet",
    description: "TV stream dispatching",
    group: "Media",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/threadfin.svg",
    tags: ["iptv", "streaming"],
  },
  {
    name: "Tautulli",
    url: "https://tautulli.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Plex activity and analytics",
    group: "Media",
    enabled: true,
    icon: "https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/favicon/favicon-32x32.png?raw=true",
    tags: ["plex", "analytics"],
  },
  {
    name: "qBittorrent",
    url: "https://torrent.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Torrent client console",
    group: "Downloads",
    enabled: true,
    icon: "https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg",
    tags: ["downloads", "torrent"],
  },
  {
    name: "Uptime Kuma",
    url: "https://uptime.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Service uptime monitor",
    group: "Operations",
    enabled: true,
    icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg",
    tags: ["uptime", "monitoring"],
  },
  {
    name: "TileServer",
    url: "https://map.tahr-vibe.ts.net",
    access: "tailnet",
    description: "Private map tiles",
    group: "Maps",
    enabled: true,
    icon: "https://raw.githubusercontent.com/maptiler/tileserver-gl/refs/heads/master/public/resources/favicon.ico",
    tags: ["maps", "tiles"],
  },
];
